### ISSUE TITLE
I Still Need the Old Version

### ISSUE THREAD

**Issue by stevenpandey** [samleong123/mediaprima_dailymotion_docker#1]
Hi mate, I still need the old version. I need m3u8 file to be able to play on my device :(

**Comment by samleong123** [comment]
Old version already deprecated , just run the docker container on ur local device and replace the M3U8 url to work

No HLS playlist will be provided as it wont work at all due to IP bind by Dailymotion

**Comment by stevenpandey** [comment]
But it still working perfectly on mobile device until yesterday when you archived this repo. I use my mobile device to watch it using .m3u8

**Comment by samleong123** [comment]
Thats weird since i've tested various ISP and different IP all return 403

For now the repo is under archived and have no plan to unarchive it

To ensure the stability of the watching experience , please use the Docker method to ensure best experience.
